<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_Sensor_NO" Id="{4d1a23dc-7a7e-4d31-8b3b-1d870d57f715}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Sensor_NO
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>